name: Your Workflow Name

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Create env file'
        env: 
          NEXT_PUBLIC_GOOGLE_ID: ${{ secrets.NEXT_PUBLIC_GOOGLE_ID }}
        run: |
          touch .env
          echo env.NEXT_PUBLIC_GOOGLE_ID > .env
          cat .env
